### ISSUE TITLE
where to set private keys with ETH

### ISSUE THREAD

**Issue by AndreiD** [lacchain/Ethereum-Benchmark#4]
hello

thank you for creating this repo
I can't find where I can sent the private key of some wallet funded with (my) ETH. I see you generate couple of random wallets, but they are all empty.
I thought there should be some sort of "master" account to fund them

Thank you again

**Comment by dweezymonae** [comment]
were you able to solve this?

**Comment by eum602** [comment]
Hi, this repo doesn't consider funded accounts, since that would require managing the balance. In addition the focus is to emulate a scenario where concurrent transactions come from anywhere. That said, the setup prior to using the repository is to set a testing network with no gas cost; with that in mind you Will be able to set random accounts to send transactions and just focus on the rate tx/s given some input conditions.

**Comment by dweezymonae** [comment]
hey i tried building the docker to test my smart contract, but i think a lot of the dependencies are outdated?
<img width="1499" alt="image" src="https://github.com/lacchain/Ethereum-Benchmark/assets/94056332/b805b637-c97a-48d3-820c-033cf65258be">

**Comment by AndreiD** [comment]
dude, I asked this 2 years ago..that's dinosaurs age in blockchain terms.
